### ISSUE TITLE
Implement this into the core directly

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-solo-lfg#3] opened 2020-05-20 17:07 UTC
After discussing this with several developers (Darkon, Diel, Yehonal), this module should be implemented into the core with configurable options. It's mostly about the .patch file

In top of that, we should be able to set a minimum amount of players required for the group size before being teleported to the dungeon AND a maximum amount of players as well.

EDIT: `game/Groups/Group.h:30:#define MAXGROUPSIZE 5`

**Comment by BarbzYHOOL** [comment] 2020-05-22 11:45
If added, need to make this configurable too:

```
server/game/DungeonFinding/LFGMgr.h:40:    LFG_GROUP_KICK_VOTES_NEEDED                  = 3
```
And do it like that: `LFG_GROUP_KICK_VOTES_NEEDED = (CONFIG_LFG_VOTE_KICK_REQUIRED_NUMBER_OF_PLAYERS) ? CONFIG_LFG_VOTE_KICK_REQUIRED_NUMBER_OF_PLAYERS; ceil(CONFIG_GROUP_MAX_PLAYERS_SIZE)`
```

**Comment by TobiMiller** [comment] 2020-06-02 11:57
+1

**Comment by elmerbud** [comment] 2020-07-18 15:08
WIP 💀

**Comment by BarbzYHOOL** [comment] 2020-07-18 17:45
Another bunch of suggestions:
- name is kinda misleading "solo-lfg" as we can "duo-lfg" "trio-lfg" etc xD, we need to find a better name for the config options :P (i'll help ofc)
- command to toggle on/off (depending on the actual state of the feature. If server is configured by default to be active, then first command usage will toggle it off for the player in question) per player. Why? that way, when the system is set to off, a solo (or duo etc...) can join the LFG system and find random players to help them

**Comment by elmerbud** [comment] 2020-07-18 20:23
I would call it `lfg-insta-pop` .

Configuration proposal:
- `LFG.insta.pop.enable` - enable insta-pop on server 
- `LFG.insta.pop.solo.enable` - enable solo (no group) insta-pop on server 
- `LFG.insta.pop.solo.command.enable` - enable player `.lfg insta pop solo on|off` command to toggle insta pop.
- `LFG.insta.pop.solo.command.announce` - announce state of `.lfg insta pop solo on|off` 
- `LFG.insta.pop.party.enable` - enable party insta-pop on server 
- `LFG.insta.pop.party.command.enable` - enable party leader`.lfg insta pop party on|off` command to toggle insta pop.
- `LFG.insta.pop.party.command.announce` - announce state of `.lfg insta pop party on|off` 
- `LFG.insta.pop.party.min.group.size` - set limit 2,3,4

LBRS/UBRS not taken into consideration yet as they are special 10-man dungeons.

**Comment by BarbzYHOOL** [comment] 2020-07-19 23:00
lfg-instapop

LFG.instapop.x.x

why the distinction between solo and party? (i can't think well atm, maybe i don't see something that could be useful :P)

what is announce state for? what would it announce?

and how do lbrs/ubrs fit in the Random Dungeon Finder tool?

**Comment by elmerbud** [comment] 2020-07-20 15:23
Because as `admin` you can choose to enable instapop for solo and party or just solo or just party. Depends how crazy `admin` is but we give him all he need.

**Comment by BarbzYHOOL** [comment] 2020-07-20 16:27
dunno if useful to tell the player, maybe it is, okay for the rest

**Comment by pangolp** [comment] 2023-06-17 22:50
Since the issue is approximately 3 years old, I will close it, and if necessary, we will reopen it. But I want to ensure that the open issues, are currently bugs or improvements that we should apply to the module today. So if we have to reopen the issue, it is reopened, or a new updated issue is created, with all the updated information, so that we can correct the error or see the possibility of implementing what was discussed here.

**Closed by pangolp** 2023-06-17 22:50 UTC
Labels: enhancement, good first issue
